# -*- coding: utf-8 -*-
"""Calculadora

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywoMZ2NRycSJFrrU-BdTLsRQHCSET-VK
"""

print("------CALCULADORA-------")
num1 = int(input("Ingrese un numero: "))
num2 = int(input("Ingrese otro numero: "))
while True:
  print("Menu de opciones")
  print("1. sumar")
  print("2. restar")
  print("3. dividir")
  print("4. multiplicar")
  opc= int(input("Ingrese una opcion: "))
  if opc == 1:
    print("La suma es: ", num1 + num2)
    break
  elif opc == 2:
    print("La resta es: ",num1 - num2)
    break
  elif opc == 3:
    print("La divison es: ",num1 / num2)
    break
  elif opc == 4:
    print("La multiplicacion es: ",num1 * num2)
    break