# -*- coding: utf-8 -*-
"""Ejercicio def

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLMbqEPbD8ibQ3JvWLzFxzc-QrJ06Ofi
"""

def saludar_alumnos():
  print("Hola alumnos, bienvenidos al curso")
saludar_alumnos() #tipo 1 sin argumentos y sin retorno

def obtener_año_actual():
  año = 2026
  nombre = "Felipe"
  edad = 28
  return nombre
print(obtener_año_actual()) #tipo 2 sin argumentos pero con retorno

nombre= input("Ingrese el nombre: ")
nota = float(input("Ingrese una nota: "))
def mostrar_estado(nombre, nota):
  if nota >= 4.0:
    estado = "aprobo el ramo"
  else:
    estado = "reprobo el ramo"
  print("Nombre: ", nombre)
  print("Estado: ", estado)
mostrar_estado(nombre, nota)

def calcular_promedio(notas):
  total = sum(notas)
  prom = total / len(notas)
  return round(prom, 1)

notas_ana = [6.5, 5.8, 7.0]
prom_ana = calcular_promedio(notas_ana)
print(f"Promedio: {prom_ana}")

def mostar_menu():
  print("1. De Celsius a Farenheit")
  print("2. De Farenheit a Celsius")
  print("3. salir")
mostar_menu()

def pedir_temperatura():
  temperatura= int(input("Ingrese la temperatura: "))
  return temperatura
print("La temperatura es: ", pedir_temperatura())

def mostrar_resultado(orig, conv, ud):
  print(orig)
  print(conv)
  print(ud)
mostrar_resultado(3.0, 40, "CF")

c = float(input("Ingrese la temperatura en celsius: "))
def celsius_a_farenheit(c):
  return (c* 9/ 5)+32
print("La temperatura a farenheit es: ", celsius_a_farenheit(c))

f = float(input("Ingrese la temperatura en farenheit: "))
def farenheit_a_celsius(f):
  return (f* - 32) * 5/9
print("La temperatura a farenheit es: ", farenheit_a_celsius(f))